"""
Project Schemas - Pydantic models for project operations
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field, field_serializer

# ============================================
# LEGACY METRIC SCHEMA (Backward Compatibility)
# ============================================


class ProjectMetric(BaseModel):
    """Legacy project metric schema - simple format"""

    primary: str
    label: str
    detail: str | None = None


# ============================================
# STANDARDIZED METRIC SCHEMAS
# ============================================


class PrimaryMetricValue(BaseModel):
    """Primary metric value with unit and label"""

    value: int | float
    unit: Literal[
        "%",
        "x",
        "$",
        "users",
        "hrs",
        "ms",
        "s",
        "min",
        "requests",
        "MB",
        "GB",
        "items",
        "calls",
    ]
    label: str = Field(
        ...,
        description="e.g., 'faster', 'cost_savings', 'users_served', 'uptime', 'time_saved'",
    )


class ComparisonValue(BaseModel):
    """Comparison value (before or after)"""

    value: int | float
    unit: Literal[
        "%",
        "x",
        "$",
        "users",
        "hrs",
        "ms",
        "s",
        "min",
        "requests",
        "MB",
        "GB",
        "items",
        "calls",
    ]


class MetricComparison(BaseModel):
    """Before/after comparison for metrics"""

    before: ComparisonValue
    after: ComparisonValue


class MetricContext(BaseModel):
    """Context for a metric (frequency and scope)"""

    frequency: Literal["daily", "weekly", "monthly", "annually", "one_time"] | None = None
    scope: str | None = Field(None, description="e.g., '200 daily users', 'entire platform', 'team of 5'")


class StandardizedProjectMetric(BaseModel):
    """Standardized project metric with structured data"""

    type: Literal["performance", "scale", "business", "quality", "time"]
    primary: PrimaryMetricValue
    comparison: MetricComparison | None = None
    context: MetricContext | None = None
    timeframe: str | None = Field(None, description="e.g., '3 months', '6 months', '1 year', 'ongoing'")


class ProjectEvidence(BaseModel):
    """Project evidence schema (screenshots only)"""

    id: str
    project_id: str
    file_path: str
    file_name: str
    file_size: int
    mime_type: str
    display_order: int
    created_at: str | datetime
    url: str | None = None  # Full URL to the image (generated by backend)

    @field_serializer("created_at")
    def serialize_datetime(self, value: str | datetime) -> str:
        """Convert datetime to ISO format string"""
        if isinstance(value, datetime):
            return value.isoformat()
        return value


class Project(BaseModel):
    """Project schema - supports both legacy and standardized metrics"""

    id: str | None = None
    company: str
    projectName: str
    role: str
    teamSize: int
    problem: str
    contributions: list[str]
    techStack: list[str]
    metrics: list[ProjectMetric | StandardizedProjectMetric]
    portfolio_id: str | None = None
    evidence: list[ProjectEvidence] | None = None


class ProjectResponse(BaseModel):
    """Project response with database fields - supports both legacy and standardized metrics"""

    id: str
    user_id: str
    company: str
    project_name: str
    role: str
    team_size: int
    problem: str
    contributions: list[str]
    tech_stack: list[str]
    display_order: int
    portfolio_id: str | None = None
    created_at: str | datetime
    updated_at: str | datetime
    metrics: list[ProjectMetric | StandardizedProjectMetric]

    @field_serializer("created_at", "updated_at")
    def serialize_datetime(self, value: str | datetime) -> str:
        """Convert datetime to ISO format string"""
        if isinstance(value, datetime):
            return value.isoformat()
        return value


class CreateProjectRequest(BaseModel):
    """Create project request - supports both legacy and standardized metrics"""

    company: str
    projectName: str
    role: str
    teamSize: int
    problem: str
    contributions: list[str]
    techStack: list[str]
    metrics: list[ProjectMetric | StandardizedProjectMetric]
    portfolio_id: str | None = None


class UpdateProjectRequest(BaseModel):
    """Update project request - supports both legacy and standardized metrics"""

    company: str | None = None
    projectName: str | None = None
    role: str | None = None
    teamSize: int | None = None
    problem: str | None = None
    contributions: list[str] | None = None
    techStack: list[str] | None = None
    metrics: list[ProjectMetric | StandardizedProjectMetric] | None = None
    portfolio_id: str | None = None


class EvidenceStatsResponse(BaseModel):
    """Evidence storage statistics response"""

    total_size_bytes: int
    limit_bytes: int
    total_size_mb: float
    limit_mb: int
    percentage_used: float
