"""
Project Schemas - Pydantic models for project operations
"""
from pydantic import BaseModel, field_serializer, Field
from typing import Optional, List, Union, Literal
from datetime import datetime


# ============================================
# LEGACY METRIC SCHEMA (Backward Compatibility)
# ============================================

class ProjectMetric(BaseModel):
    """Legacy project metric schema - simple format"""
    primary: str
    label: str
    detail: Optional[str] = None


# ============================================
# STANDARDIZED METRIC SCHEMAS
# ============================================

class PrimaryMetricValue(BaseModel):
    """Primary metric value with unit and label"""
    value: Union[int, float]
    unit: Literal["%", "x", "$", "users", "hrs", "ms", "s", "min", "requests", "MB", "GB", "items", "calls"]
    label: str = Field(..., description="e.g., 'faster', 'cost_savings', 'users_served', 'uptime', 'time_saved'")


class ComparisonValue(BaseModel):
    """Comparison value (before or after)"""
    value: Union[int, float]
    unit: Literal["%", "x", "$", "users", "hrs", "ms", "s", "min", "requests", "MB", "GB", "items", "calls"]


class MetricComparison(BaseModel):
    """Before/after comparison for metrics"""
    before: ComparisonValue
    after: ComparisonValue


class MetricContext(BaseModel):
    """Context for a metric (frequency and scope)"""
    frequency: Optional[Literal["daily", "weekly", "monthly", "annually", "one_time"]] = None
    scope: Optional[str] = Field(None, description="e.g., '200 daily users', 'entire platform', 'team of 5'")


class StandardizedProjectMetric(BaseModel):
    """Standardized project metric with structured data"""
    type: Literal["performance", "scale", "business", "quality", "time"]
    primary: PrimaryMetricValue
    comparison: Optional[MetricComparison] = None
    context: Optional[MetricContext] = None
    timeframe: Optional[str] = Field(None, description="e.g., '3 months', '6 months', '1 year', 'ongoing'")


class ProjectEvidence(BaseModel):
    """Project evidence schema (screenshots only)"""
    id: str
    project_id: str
    file_path: str
    file_name: str
    file_size: int
    mime_type: str
    display_order: int
    created_at: Union[str, datetime]
    url: Optional[str] = None  # Full URL to the image (generated by backend)
    
    @field_serializer('created_at')
    def serialize_datetime(self, value: Union[str, datetime]) -> str:
        """Convert datetime to ISO format string"""
        if isinstance(value, datetime):
            return value.isoformat()
        return value


class Project(BaseModel):
    """Project schema - supports both legacy and standardized metrics"""
    id: Optional[str] = None
    company: str
    projectName: str
    role: str
    teamSize: int
    problem: str
    contributions: List[str]
    techStack: List[str]
    metrics: List[Union[ProjectMetric, StandardizedProjectMetric]]
    portfolio_id: Optional[str] = None
    evidence: Optional[List[ProjectEvidence]] = None


class ProjectResponse(BaseModel):
    """Project response with database fields - supports both legacy and standardized metrics"""
    id: str
    user_id: str
    company: str
    project_name: str
    role: str
    team_size: int
    problem: str
    contributions: List[str]
    tech_stack: List[str]
    display_order: int
    portfolio_id: Optional[str] = None
    created_at: Union[str, datetime]
    updated_at: Union[str, datetime]
    metrics: List[Union[ProjectMetric, StandardizedProjectMetric]]
    
    @field_serializer('created_at', 'updated_at')
    def serialize_datetime(self, value: Union[str, datetime]) -> str:
        """Convert datetime to ISO format string"""
        if isinstance(value, datetime):
            return value.isoformat()
        return value


class CreateProjectRequest(BaseModel):
    """Create project request - supports both legacy and standardized metrics"""
    company: str
    projectName: str
    role: str
    teamSize: int
    problem: str
    contributions: List[str]
    techStack: List[str]
    metrics: List[Union[ProjectMetric, StandardizedProjectMetric]]
    portfolio_id: Optional[str] = None


class UpdateProjectRequest(BaseModel):
    """Update project request - supports both legacy and standardized metrics"""
    company: Optional[str] = None
    projectName: Optional[str] = None
    role: Optional[str] = None
    teamSize: Optional[int] = None
    problem: Optional[str] = None
    contributions: Optional[List[str]] = None
    techStack: Optional[List[str]] = None
    metrics: Optional[List[Union[ProjectMetric, StandardizedProjectMetric]]] = None
    portfolio_id: Optional[str] = None


class EvidenceStatsResponse(BaseModel):
    """Evidence storage statistics response"""
    total_size_bytes: int
    limit_bytes: int
    total_size_mb: float
    limit_mb: int
    percentage_used: float

